#! /bin/sh

# VitualBox intergration
VBoxClient-all

# Imwheel
imwheel &

# Compsitor
 # picom &

# Set Theme
wal -R

# ~/.config/polybar/launch.sh &
eww open bar


~/.config/bspwm/scripts/swallow &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config ignore_ewmh_struts true

bspc monitor -d 1 2 3 4
bspc monitor Virtual2 -d 6 7 8 9

bspc config window_gap 47
bspc config -m Virtual1 bottom_padding 77
bspc config -m Virtual1 top_padding 0

bspc config border_width 1

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# feh --bg-max -B "$color0" ~/.wallpapers/Background.png

# Set the border colors.
bspc config normal_border_color "$color9"
bspc config active_border_color "$color9"
bspc config focused_border_color "$color9"

# Use the line below iyou are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"

bash /home/evan/.config/bspwm/bspwm_colors.sh &

xsetroot -cursor_name left_ptr

export GTK_THEME=Lavanda-Sea-Dark
export ICON_THEME=Colloid-dark
