#! /bin/sh

#  ███████████                                                   
# ░░███░░░░░███                                                  
#  ░███    ░███  █████  ████████  █████ ███ █████ █████████████  
#  ░██████████  ███░░  ░░███░░███░░███ ░███░░███ ░░███░░███░░███ 
#  ░███░░░░░███░░█████  ░███ ░███ ░███ ░███ ░███  ░███ ░███ ░███ 
#  ░███    ░███ ░░░░███ ░███ ░███ ░░███████████   ░███ ░███ ░███ 
#  ███████████  ██████  ░███████   ░░████░████    █████░███ █████
# ░░░░░░░░░░░  ░░░░░░   ░███░░░     ░░░░ ░░░░    ░░░░░ ░░░ ░░░░░ 
#                       ░███                                     
#                       █████                                    
#                      ░░░░░

~/.config/polybar/launch.sh &
~/.config/bspwm/scripts/swallow &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config ignore_ewmh_struts   true

bspc monitor -d 1 2 3 4 5
bspc monitor Virtual2 -d 6 7 8 9

bspc config window_gap          47
bspc config -m Virtual1 top_padding 66

bspc config border_radius         13
bspc config border_width         1

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color2"
bspc config active_border_color "$color15"
bspc config focused_border_color "$color1"

# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
